version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5000"
    environment:
      DATABASE_URL: "postgres://postgres:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
